/* 
 * LIO - Order Management API
 *
 * API de gerenciamento de pedidos da LIO.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrdersTransactions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrdersTransactionsTests
    {
        // TODO uncomment below to declare an instance variable for OrdersTransactions
        //private OrdersTransactions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrdersTransactions
            //instance = new OrdersTransactions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrdersTransactions
        /// </summary>
        [Test]
        public void OrdersTransactionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrdersTransactions
            //Assert.IsInstanceOfType<OrdersTransactions> (instance, "variable 'instance' is a OrdersTransactions");
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TransactionType'
        /// </summary>
        [Test]
        public void TransactionTypeTest()
        {
            // TODO unit test for the property 'TransactionType'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TerminalNumber'
        /// </summary>
        [Test]
        public void TerminalNumberTest()
        {
            // TODO unit test for the property 'TerminalNumber'
        }
        /// <summary>
        /// Test the property 'Card'
        /// </summary>
        [Test]
        public void CardTest()
        {
            // TODO unit test for the property 'Card'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'AuthorizationCode'
        /// </summary>
        [Test]
        public void AuthorizationCodeTest()
        {
            // TODO unit test for the property 'AuthorizationCode'
        }
        /// <summary>
        /// Test the property 'PaymentProduct'
        /// </summary>
        [Test]
        public void PaymentProductTest()
        {
            // TODO unit test for the property 'PaymentProduct'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
